=begin
Uber API

Move your app forward with the Uber API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class DefaultController < ApplicationController

  def bill_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def transaction_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
