# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: User API
  description: Move your app forward with the User API
  version: "1.0.0"
# the domain of the service
host: localhost:5000
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /me:
    get:
      summary: User User
      description: The User User endpoint returns information about the Uber user that has authorized with the application.
      tags:
        - User
      responses:
        200:
          description: User information for a user
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      parameters:
        - name: user
          in: body
          description: The user JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      responses:
        200:
          description: Make a new user
    put:
      parameters:
        - name: user
          in: body
          description: The user JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      responses:
        200:
          description: Updates the user
definitions:
  User:
    type: object
    properties:
      user_id:
        type: string
        description: identifier of Uber user.
      name:
        type: string
        description: Name of the Uber user.
      email:
        type: string
        description: Email address of the Uber user
      sex:
        type: number
        description: Sex of the Uber user.
      rate:
        type: number
        description: Rate of the User
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string