=begin
Product API

Move your app forward with the Uber API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table "product".pluralize.to_sym, id: false do |t|
      t.string :product_id
      t.string :description
      t.string :display_name
      t.string :capacity
      t.float :price

      t.timestamps
    end

  end
end
