=begin
User API

Move your app forward with the User API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table "profile".pluralize.to_sym, id: false do |t|
      t.string :user_id
      t.string :name
      t.string :email
      t.float :sex
      t.float :rate
      t.string :promo_code

      t.timestamps
    end

  end
end
