=begin
Uber API

Move your app forward with the Uber API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/v1/bill', controller_name: 'default', action_name: 'bill_get'
  add_swagger_route 'GET', '/v1/history', controller_name: 'default', action_name: 'history_get'
  add_swagger_route 'POST', '/v1/transaction', controller_name: 'default', action_name: 'transaction_post'
end
