=begin
User API

Move your app forward with the User API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class DefaultsController < ApplicationController

  def me_post
    # Your code here
    used_params = permit_params
    puts(used_params)
    me = User.create(used_params)

    render :json => me
  end

  def permit_params
  	params.permit(:name, :user_id, :email, :sex, :rate)
  end
end
