=begin
User API

Move your app forward with the User API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def me_get
    # Your code here
    me = User.first
    render :json => me
    # render json: {"message" => "yes, it worked"}
  end
end
